h

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,38 +27,39 @@ job1:
 job2:
   stage: build
   script:
-    - echo "Setting up SSH configuration"
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - echo "$PKEY_FILE" > ~/.ssh/id_rsa
-    - chmod 600 .ssh/id_rsa
-    - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
-    - chmod 600 .ssh/known_hosts
+  - echo "Setting up SSH configuration"
+  - mkdir -p ~/.ssh
+  - chmod 700 ~/.ssh
+  - echo "$PKEY_FILE" > ~/.ssh/id_rsa
+  - chmod 600 ~/.ssh/id_rsa
+  - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
+  - chmod 600 ~/.ssh/known_hosts
 
-    - echo "Testing SSH connection to $ip"
-    - |
-      if ! ssh -i .ssh/id_rsa -T azureuser@$ip "echo 'SSH connection successful'"; then
-        echo "ERROR: SSH connection failed" >&2
-        exit 1
-      fi
+  - echo "Testing SSH connection to $ip"
+  - |
+    if ! ssh -i ~/.ssh/id_rsa -T azureuser@$ip "echo 'SSH connection successful'"; then
+      echo "ERROR: SSH connection failed" >&2
+      exit 1
+    fi
 
-    - echo "Running remote deployment commands"
-    - |
-      ssh -i .ssh/id_rsa -T azureuser@$ip <<EOF
-        set -e
-        echo "Logging into Docker registry"
-        echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
+  - echo "Running remote deployment commands"
+  - |
+    ssh -i ~/.ssh/id_rsa -T azureuser@$ip <<EOF
+      set -e  # Stop on error
+      echo "Logging into Docker registry"
+      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
 
-        echo "Pulling Docker image"
-        docker pull ganeshd2532/prod_data:$DOCKER_IMAGE
+      echo "Pulling Docker image"
+      docker pull ganeshd2532/prod_data:$CI_COMMIT_SHA
 
-        echo "Pruning unused containers and images"
-        docker container prune -f
-        docker image prune -f
+      echo "Pruning unused containers and images"
+      docker container prune -f
+      docker image prune -f
 
-        echo "Running Docker container"
-        docker run -d -p 5432:5432 -p 5000:5000 -p 80:80 $DOCKER_IMAGE
+      echo "Running Docker container"
+      docker run -d -p 5432:5432 -p 5000:5000 -p 80:80 ganeshd2532/prod_data:$CI_COMMIT_SHA
 
-        echo "Deployment complete"
-      EOF
       echo "Deployment complete"
+    EOF
+
+  - echo "Deployment completed successfully"
